sudo: require
language: generic

services:
  - docker

before_install:
  - docker build -t ajm2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ajm2/react-test npm test

after_success:
  - docker build -t ajm2/multi-client ./client
  - docker build -t ajm2/multi-nginx ./nginx
  - docker build -t ajm2/multi-server ./server
  - docker build -t ajm2/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push ajm2/multi-client
  - docker push ajm2/multi-nginx
  - docker push ajm2/multi-server
  - docker push ajm2/multi-worker